@startuml
class com.example.altezachen3.LoginActivity {
~ Button signUp
- FirebaseAuth mAuth
~ String email
~ String password
~ EditText emailPre
~ EditText passwordPre
~ BroadcastReceiver broadcastReceiver
~ FirebaseFirestore db
~ Intent logToCraeteAccount
~ Integer REQUEST_CODE_PERMISSIONS
~ ProgressBar pr
# void onCreate(Bundle)
- void loadData()
# void registerNetworkBroadcastReciver()
# void unregisterNetwork()
# void onDestroy()
+ void onStart()
+ void onRequestPermissionsResult(int,String[],int[])
+ void onClick(View)
- void reload()
}
class com.example.altezachen3.Profile {
# String accountName
# String accountEmail
# ArrayList<String> wishListItemsID
# String phoneNumber
# String profilePicturePath
# boolean isSeller
+ <<Create>> Profile()
+ <<Create>> Profile(String,String,String,String)
+ boolean isSeller()
+ void setSeller(boolean)
+ String getProfilePicturePath()
+ void setProfilePicturePath(String)
+ String getAccountName()
+ void setAccountName(String)
+ String getAccountEmail()
+ void setAccountEmail(String)
+ ArrayList<String> getWishListItemsID()
+ void setWishListItemsID(ArrayList<String>)
+ String getPhoneNumber()
+ void setPhoneNumber(String)
+ String toString()
}
class com.example.altezachen3.BasicActivity {
- FirebaseAuth mAuth
~ FirebaseFirestore db
~ Profile user
~ ProfileManufacturer user2
~ StorageReference storageReference
# void onCreate(Bundle)
+ boolean onCreateOptionsMenu(Menu)
+ boolean onOptionsItemSelected(MenuItem)
}
class com.example.altezachen3.GridView {
~ FirebaseFirestore db
~ android.widget.GridView GVAllItems
~ ArrayList<Item> alAllItems
~ ItemsGVAdapter adapter
~ ProgressBar progressBar
~ BottomNavigationView bottomNavigationView
~ SearchView searchView
~ ToggleButton price
~ ImageView sort
~ ArrayList<String> userFav
~ Boolean priceSort
# void onCreate(Bundle)
- void loadData()
- void loadFav()
- void loadItemsToGridView()
+ boolean onNavigationItemSelected(MenuItem)
+ boolean onQueryTextSubmit(String)
+ boolean onQueryTextChange(String)
+ void onClick(View)
- void filterByField(ArrayList<Item>,String,Query.Direction,String,Query.Direction)
}
class com.example.altezachen3.Item {
- String idItem
- String itemName
- double itemPrice
- int itemQuantity
- ItemSize itemSize
- String category
+ String itImagePath
+ String creatorMail
+ <<Create>> Item()
+ <<Create>> Item(String,double,int,ItemSize,String,String,String)
+ String getItemName()
+ void setItemName(String)
+ double getItemPrice()
+ void setItemPrice(double)
+ int getItemQuantity()
+ void setItemQuantity(int)
+ ItemSize getItemSize()
+ void setItemSize(ItemSize)
+ String getCategory()
+ void setCategory(String)
+ String getIdItem()
+ void setIdItem(String)
+ String getItImagePath()
+ void setItImagePath(String)
+ String getCreatorMail()
+ void setCreatorMail(String)
+ String toString()
}
class com.example.altezachen3.UserCreate {
- FirebaseAuth mAuth
~ FirebaseUser currentUser
~ FirebaseFirestore db
~ StorageReference storageRef
~ FirebaseStorage storage
~ TextView usermail
~ Button sumbitUser
~ ImageView profilePicture
~ CardView imgCardView
~ EditText userName
~ Intent galleryAdd
~ String imgPath
~ CountryCodePicker codePicker
~ CheckBox isManufacturer
~ Uri uri
~ int REQUEST_IMAGE_CAPTURE
~ ActivityResultLauncher<Intent> someActivityResultLauncher
# void onCreate(Bundle)
+ void onStart()
+ void onClick(View)
- Profile createUser()
+ boolean checkData()
- void UploadPhoto()
+ Uri getImageUri(Context,Bitmap)
+ void onActivityResult(int,int,Intent)
- void openCamera()
+ String itemPath()
}
class com.example.altezachen3.ItemSize {
- double itemX
- double itemY
- double itemZ
+ <<Create>> ItemSize()
+ <<Create>> ItemSize(double,double,double)
+ double getItemX()
+ void setItemX(double)
+ double getItemY()
+ void setItemY(double)
+ double getItemZ()
+ void setItemZ(double)
+ double Volume()
+ String toString()
}
class com.example.altezachen3.ProfileGVAdapter {
~ FirebaseFirestore db
~ int pos
~ Item item
~ TextView itemNameGridView
~ StorageReference storageReference
~ ImageView photoView
~ CardView cardView
~ Activity ac
+ <<Create>> ProfileGVAdapter(Context,ArrayList<Item>)
+ View getView(int,View,ViewGroup)
+ {static} int getScreenWidth(Activity)
+ {static} int getScreenHeight(Activity)
}
class com.example.altezachen3.ItemPost {
~ Button add
- FirebaseAuth mAuth
~ {static} int REQUEST_IMAGE_CAPTURE
~ FirebaseUser currentUser
~ FirebaseFirestore db
~ Uri uri
~ Boolean update
~ Bitmap image
~ Boolean isSeller
~ TextView txUserName
~ EditText preItName
~ String itName
~ Item item1
~ ItemSize size1
~ Intent intentToListView
~ Spinner spCatagory
~ StorageReference storageRef
~ FirebaseStorage storage
~ ImageView photo
~ BottomNavigationView bottomNavigationView
~ TextView hint
~ ActivityResultLauncher<Intent> someActivityResultLauncher
# void onCreate(Bundle)
+ void onStart()
+ void onClick(View)
- void dispatchTakePictureIntent()
- boolean checkItemValues()
- void openCamera()
+ Uri getImageUri(Context,Bitmap)
+ void onActivityResult(int,int,Intent)
- void UploadPhoto2()
+ String itemPath()
+ Item createItem()
+ void onItemSelected(AdapterView<?>,View,int,long)
+ void onNothingSelected(AdapterView<?>)
+ boolean onNavigationItemSelected(MenuItem)
}
class com.example.altezachen3.ActivityProfile {
- CardView prCardView
- ImageView prPicture
- TextView prName
~ android.widget.GridView prGridView
- FirebaseAuth mAuth
~ FirebaseUser currentUser
~ FirebaseFirestore db
~ StorageReference storageReference
~ FirebaseStorage storage
~ Profile user
~ ProfileGVAdapter adapter
~ ArrayList<String> userPosts
~ ProfileManufacturer userSeller
~ BottomNavigationView bottomNavigationView
~ ArrayList<Item> alAllItems
~ DocumentSnapshot doc
~ String userFromOther
# void onCreate(Bundle)
- void loadToGridView(String)
- void loadingUserPosts(String)
+ boolean onNavigationItemSelected(MenuItem)
+ void onClick(View)
}
class com.example.altezachen3.ProfileManufacturer {
- String location
- ArrayList<String> postsList
+ <<Create>> ProfileManufacturer()
+ <<Create>> ProfileManufacturer(String,String,String,String,String)
+ String getLocation()
+ void setLocation(String)
+ ArrayList<String> getPostsList()
+ void setPostsList(ArrayList<String>)
+ String toString()
}
class com.example.altezachen3.WiFiConnectioOn {
+ void onReceive(Context,Intent)
+ boolean isOnline(Context)
}
class com.example.altezachen3.ItemsGVAdapter {
~ FirebaseFirestore db
~ int pos
~ Item item
~ TextView itemNameGridView
~ StorageReference storageReference
~ ImageView photoView
~ CardView cardView
~ Activity ac
~ Context acContext
+ <<Create>> ItemsGVAdapter(Context,ArrayList<Item>)
+ View getView(int,View,ViewGroup)
+ {static} int getScreenWidth(Activity)
+ {static} int getScreenHeight(Activity)
}
class com.example.altezachen3.MyFirebaseMessagingService {
- {static} String TAG
~ String CHANNEL_ID
+ void onMessageReceived(RemoteMessage)
}
class com.example.altezachen3.MyAppGlideModule {
+ void registerComponents(Context,Glide,Registry)
}
class com.example.altezachen3.ItemShow {
~ ImageView itemImage
- FirebaseAuth mAuth
~ FirebaseUser currentUser
~ FirebaseFirestore db
~ StorageReference storageReference
~ TextView itName
~ ToggleButton wishlist
~ CardView creatorCV
~ String phoneNumber
~ boolean isButtonAddToFavPressed
~ Item item
# void onCreate(Bundle)
+ void onClick(View)
+ void changingWishList(boolean)
}


com.example.altezachen3.OnClickListener <|.. com.example.altezachen3.LoginActivity
androidx.appcompat.app.AppCompatActivity <|-- com.example.altezachen3.LoginActivity
androidx.appcompat.app.AppCompatActivity <|-- com.example.altezachen3.BasicActivity
com.example.altezachen3.OnItemSelectedListener <|.. com.example.altezachen3.GridView
com.example.altezachen3.OnQueryTextListener <|.. com.example.altezachen3.GridView
com.example.altezachen3.OnClickListener <|.. com.example.altezachen3.GridView
com.example.altezachen3.BasicActivity <|-- com.example.altezachen3.GridView
java.io.Serializable <|.. com.example.altezachen3.Item
com.example.altezachen3.OnClickListener <|.. com.example.altezachen3.UserCreate
com.example.altezachen3.BasicActivity <|-- com.example.altezachen3.UserCreate
java.io.Serializable <|.. com.example.altezachen3.ItemSize
android.widget.ArrayAdapter <|-- com.example.altezachen3.ProfileGVAdapter
com.example.altezachen3.OnClickListener <|.. com.example.altezachen3.ItemPost
com.example.altezachen3.OnItemSelectedListener <|.. com.example.altezachen3.ItemPost
com.example.altezachen3.OnItemSelectedListener <|.. com.example.altezachen3.ItemPost
com.example.altezachen3.BasicActivity <|-- com.example.altezachen3.ItemPost
com.example.altezachen3.OnItemSelectedListener <|.. com.example.altezachen3.ActivityProfile
com.example.altezachen3.OnClickListener <|.. com.example.altezachen3.ActivityProfile
com.example.altezachen3.BasicActivity <|-- com.example.altezachen3.ActivityProfile
com.example.altezachen3.Profile <|-- com.example.altezachen3.ProfileManufacturer
android.content.BroadcastReceiver <|-- com.example.altezachen3.WiFiConnectioOn
android.widget.ArrayAdapter <|-- com.example.altezachen3.ItemsGVAdapter
com.google.firebase.messaging.FirebaseMessagingService <|-- com.example.altezachen3.MyFirebaseMessagingService
com.bumptech.glide.module.AppGlideModule <|-- com.example.altezachen3.MyAppGlideModule
com.example.altezachen3.OnClickListener <|.. com.example.altezachen3.ItemShow
com.example.altezachen3.BasicActivity <|-- com.example.altezachen3.ItemShow
@enduml